trigger:
- main  # Change this if needed

pool:
  vmImage: 'ubuntu-latest'  # Use an Azure DevOps pre-configured agent pool

steps:
- task: Checkout@1  # Ensure the code is checked out first

- script: |
    echo "Listing files in the repository"
    dir $(Build.SourcesDirectory)
  displayName: 'List files in repository'

- task: Maven@4
  inputs:
    mavenPomFile: '$(Build.SourcesDirectory)/pom.xml'  # Update this path if necessary
    mavenOptions: '-Xmx3072m'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.11'
    jdkArchitectureOption: 'x64'
    publishJUnitResults: true
    testResultsFiles: '**/surefire-reports/TEST-*.xml'
    goals: 'package'
